[package]
name = "why_blocking_threads"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["hickory-dns"] }
tokio = { version = "1.42.0", features = ["rt-multi-thread", "macros"] }
